#!/bin/sh

uci show gluon.core.domain
retVal=$?

uci show gluon.core.domain | grep -vi legacy
retVal2=$?

if [ $retVal -ne 0 -o $retVal2 -ne 0 ]; then
  uci set gluon.core.domain='nordstadt'
  uci commit gluon.core.domain
fi
