#!/bin/sh

public=23b70f506580bb50b5727297a7e73389fad453812d779d948680148bcd21293f
addr=update-verify.ffh

challenge="$(uci show network.bat0.macaddr | cut -d"=" -f 2)"

while true; do

	response=$(echo -n "CHALLENGE:$challenge" | nc $addr 12345)

	if echo -n "$challenge" | ecdsaverify -p $public -s "$response"; then
		echo -n "UPDATE:$challenge" | nc $addr 12345 || continue # if you can't report, that you' are updating now
		echo "UPDATE NOW!"
		exit 0;
	else
		echo "WRONG SIGNATURE!"
	fi

	sleep 30;
done;
