#!/bin/sh

# /lib/gluon/upgrade/0200-site-adjust.lua actually patches the site.conf
# we need to trigger all scripts in /lib/gluon/upgrade/*
# since they depend on the site.conf.
for script in /lib/gluon/upgrade/*; do
	"$script"
done

# we use an existing br-setup as indicator that we
# are in the config mode.
if ! ip link show br-setup 2>/dev/null 1>/dev/null; then
	# since this script is also called by luci (aka gluon-web), it's
	# important that we do not reboot in this case. we ensure
	# this by not rebooting in config mode at all.
	reboot
	logger -s -t site-upgrade "rebooting now."
fi
