#!/usr/bin/lua

-- ask for a district updrade hourly. the minute is chosen randomly
local minute = math.random(0, 59)

local f = io.open('/usr/lib/micron.d/migrate-districts', 'w')
f:write(string.format('%i * * * * /lib/gluon/district-migrate\n', minute))
