#!/bin/sh

node_id=$(cat /lib/gluon/core/sysconfig/primary_mac | tr -d ':')

old_district=$(uci get gluon-node-info.district.current)
new_district=$(wget http://web.ffh.zone/migrate/${node_id} -O - -q)

if [ $? -ne 0 ]; then
	logger -s -t district-migrate "can't wget!"
	exit
fi

if [ "$old_district" == "$new_district" ]; then
	echo district-migrate: nothing to do 1>&2
	exit
fi

uci set gluon-node-info.district=district
uci set gluon-node-info.district.current=${new_district}
uci commit gluon-node-info

logger -s -t district-migrate "switching to district ${new_district}."
/lib/gluon/district-changed.sh
